name: diana
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/carmonac/diana
environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  analyzer: ^7.4.5
  build: ^2.5.3
  code_builder: ^4.10.1
  dart_style: ^3.1.0
  glob: ^2.1.3
  meta: ^1.17.0
  path: ^1.9.1
  shelf: ^1.4.2
  shelf_cors_headers: ^0.1.5
  shelf_router: ^1.1.4
  shelf_static: ^1.1.3
  shelf_web_socket: ^3.0.0
  source_gen: ^2.0.0
  uuid: ^4.5.1
# path: ^1.8.0
dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
