name: diana
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://github.com/carmonac/diana
environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  analyzer: ^7.4.5
  build: ^2.5.3
  code_builder: ^4.10.1
  crypto: ^3.0.6
  dart_style: ^3.1.0
  get_it: ^8.0.3
  glob: ^2.1.3
  http_parser: ^4.0.2
  meta: ^1.17.0
  mime: ^2.0.0
  path: ^1.9.1
  shelf: ^1.4.2
  shelf_cors_headers: ^0.1.5
  shelf_multipart: ^2.0.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.3
  shelf_web_socket: ^3.0.0
  source_gen: ^2.0.0
  web_socket_channel: ^3.0.3

dev_dependencies:
  build_runner: ^2.4.13
  lints: ^5.0.0
  test: ^1.24.0
